POST http://localhost:4000/api/promociones/
Content-Type: application/json

{
  "promocion": "Nombre de la Promoción",
  "fecha_inicio": "2023-11-26T00:00:00.000Z",
  "fecha_final": "2023-12-31T23:59:59.999Z",
  "descuento": 10,
  "descripcion": "Descripción de la promoción",
  "estado": true,
  "cantidad_Articulos": 100
  }