POST http://localhost:4000/api/eventos
Content-Type: application/json

{
  "titulo": "Feria de Adopción",
  "descripcion": "Evento para encontrar un hogar a perros y gatos rescatados.",
  "ubicacion": "Parque Central",
  "fechaInicio": "2025-09-25T10:00:00.000Z",
  "fechaFin": "2025-09-25T15:00:00.000Z",
  "estado": true,
  "organizadorId": "68c6f6510c0a40556d6ada5d"
}
