POST  http://localhost:4000/api/detalleventa/
Content-Type: application/json


{
  "id_ventas": "6597479869b0f339f12132e5",
  "articulos": [
    {
      "id_articulo": "658ef455ac75aed855a4ec25",
      "id_marca": "6566b1ff1693e94218aabf6e",
      "id_color": "6566b0ad1693e94218aabf51",
      "id_estilo": "6584658fef6c4c4663141a25",
      "id_material": "656156daf9c6ffbe9552ecf2",
      "id_talla": "6585dce4f8cb50dfa8178bb1",
      "id_diseño": "65387375e2fbfdbd8119fe5c",
      "cantidad": 10,
      "precio": 20.5,
      "subtotal": 205,
      "descuento": 5
    }
   
  ],
  "total": 2000
}
