curl -X PUT http://localhost:4000/api/mascotas-perdidas/68d03ace0b9c87548d4d3afc \
  -H "Content-Type: application/json" \
  -d '{
    "descripcion": "Perro labrador negro, muy juguetón, lleva collar rojo y placa de identificación.",
    "estado": "encontrada"
  }'
