@api = http://localhost:4000/api/auth

### Signin
POST {{api}}/signup
Content-Type: application/json

{
  "username":"ken",
  "email": "ken@gmail.com",
  "password": "1234",
  "roles":["admin", "user","moderator"]
  
}